
DELETE FROM votes WHERE 1 = 1;
DELETE FROM reviewers WHERE 1 = 1;

DELETE FROM drafts WHERE 1 = 1;
DELETE FROM reviews WHERE 1 = 1;

DELETE FROM films WHERE 1 = 1;

DELETE FROM SQLITE_SEQUENCE WHERE name = 'films';
DELETE FROM SQLITE_SEQUENCE WHERE name = 'reviews';
DELETE FROM SQLITE_SEQUENCE WHERE name = 'drafts';
DELETE FROM SQLITE_SEQUENCE WHERE name = 'votes';
DELETE FROM SQLITE_SEQUENCE WHERE name = 'reviewers';


DELETE FROM reviews WHERE id = 13 or id = 24;